version: '2.4'
services:
  db:
    image: mysql
    container_name: mysql-task-tracker
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - task_list_tracker_data:/var/lib/mysql

volumes:
  task_list_tracker_data: